import os, matplotlib, openpyxl, json
import pandas as pd
import datetime as dt
from copy import deepcopy


def build_league(teams_dict=None, league_name=None):
    """
    this function builds a league:
    1) for the first time from a dictionary of competitors or teams, or
    2) from archived .json data of a pre-existing league generated by this application
    
    To generate a league for the first time:
    you must also provide a string for the keyword argument league_name.
    the first argument for this function must take the form of one dictionary for each team, each nested inside one larger dictionary.
    
    for example:
    
    team_dict = {
        '<team1>': {
            'name': '<City1 Mascot1>',
            'code': '<CITYABBREVIATION>',
            'division': '<northdivision>'
        },
        '<team2>': {
            'name': '<City2 Mascot2>',
            'code': '<CITY2ABBREVIATION>',
            'division': '<southdivision>'
        }
    }
    
    the team1, team2, etc... keys may be anything you wish (i recommend some shorthand that's easy to remember e.g., just use the code again).
    but the function expects to see the keys 'name', 'code', and 'division' in the nested dictionaries.
    
    for example:
    
    team_dict = {
        'det': {
            'name': 'Detroit Lions',
            'code': 'DET',
            'division': 'NFCN'
        },
        'ind': {
            'name': 'Indianapolis Colts',
            'code': 'IND',
            'division': 'AFCS'
        }
    }
    
    to build a league from preexisting data:
    provide a file name and build_league will look for a .json file with that name in the data subdirectory.
    """ 
    file_input = False
    if teams_dict == None:
        file_input = True
        print("attempting to import data...")
        for i in range(52, 0, -1):
            teams_dict = f"data/week{i}.json"
            try:
                file = open(teams_dict)
            except FileNotFoundError:
                pass
            else:
                teams_dict = json.load(file)
                file.close()
                print(f">>> data successfully imported from data/week{i}.json")
                break
    if type(teams_dict) == str:
        file_input = True
        if teams_dict[-5:] == ".json":
            pass
        else:
            teams_dict = teams_dict + ".json"
        teams_dict = "data/" + teams_dict
        print(f"attempting to import data from {teams_dict}...")
        file = open(teams_dict)
        teams_dict = json.load(file)
        file.close()
        print(">>> data successfully imported")
    if type(teams_dict) == dict:
        working_dict = deepcopy(teams_dict)
        try:
            teams = {}
            for key, value in working_dict['_teams'].items(): 
                name = value['_name']
                code = value['_code']
                div = value['_division']
                del value['_name']
                del value['_code']
                del value['_division']
                teams[key] = Team(name, code, div, **value)
            del working_dict['_teams']
            league = League(teams, **working_dict)
            league._add_opps()
        except KeyError:
            for value in teams_dict.values():
                value['code'] = value['code'].lower()  
            league = {
                key: Team(value['name'], value['code'], value['division'])
                for key, value in teams_dict.items()
            }
            league = League(league)
    else:
        raise Exception("error: please provide either a dictionary of teams or a path to a .json file containing a dictionary of teams")
    if file_input == False:
        file_name = "data/" + league_name + ".json"
        try:
            file = open(file_name, "wt")
        except FileNotFoundError:
            os.mkdir("data")
            file = open(file_name, "wt")
        json.dump(teams_dict, file)
        file.close()
        print(f"league data successfully exported as {file_name}")
    return league


class League:


    def __init__(self, team_dict, _weeks_complete=0, _max_pt_diff=0, _max_power_score=0, _min_power_score=0):
        self._teams = team_dict
        self._weeks_complete = _weeks_complete
        self._max_pt_diff = _max_pt_diff
        self._max_power_score = _max_power_score
        self._min_power_score = _min_power_score
    
    
    def __str__(self):
        return f"{[value.get_name() for value in self._teams.values()]}"
    
    
    def get_team(self, code):
        return self._teams[code]
    
    
    def _add_opps(self):
        for team in self._teams.values():
            for week in team._week:
                week['opp'] = self.get_team(week['opp_code'])
    
    
    def build_df(self):
        header = ["Pwr Rank", "Tier", "Team", "Win", "Loss", "Tie", "Win%", "Tot Pt Diff", "SoS",
                  "Last4", "Pwr Score", "Scaled Pwr Score"
                 ]
        for i in range(self._weeks_complete+1):
            header.extend([f"Week {i+1}", f"Opp{i+1}", f"Score{i+1}", f"OppScore{i+1}"])
        data = [team.build_df() for team in self._teams.values()]
        return pd.DataFrame(data, columns=header)


    def build_csv(self, order='alpha'):
        file_name = "power_rankings.csv"
        df = self.build_df()
        if order == 'alpha':
            df.to_csv(file_name, index=False)
            print(f"data successfully exported as {file_name}")
        elif order == 'rank':
            df.sort_values(by="Pwr Rank").to_csv(file_name, index=False)
            print(f"data successfully exported as {file_name}")
        elif order == 'win%':
            df.sort_values(by="Win%").to_csv(file_name, index=False)
            print(f"data successfully exported as {file_name}")
        elif order == 'pt_diff':
            df.sort_values(by="Tot Pt Diff").to_csv(file_name, index=False)
            print(f"data successfully exported as {file_name}")
        else:
            print("""error: please select a valid sort order:
            rank (default), alpha, win%, pt_diff""")


    def build_xlsx(self, order='rank'):
        df = self.build_df()
        if order == 'rank':
            df = df.sort_values(by="Pwr Rank")
        elif order == 'alpha':
            pass
        elif order == 'win%':
            df = df.sort_values(by="Win%")
        elif order == 'pt_diff':
            df = df.sort_values(by="Tot Pt Diff")
        else:
            print("""error: please select a valid sort order:
            rank (default), alpha, win%, pt_diff""")
        styled_df = df.style.background_gradient(subset = ["Pwr Rank", "Tier"], cmap='RdYlGn_r').background_gradient(subset = ["SoS", "Scaled Pwr Score"], cmap='RdYlGn')
        file_name = "power_rankings.xlsx"
        styled_df.to_excel(file_name, index=False)
        print(f"data successfully exported as {file_name}")


    def game(self, away_team, away_score, home_team, home_score):
        if abs(away_score - home_score) > self._max_pt_diff:
            self._max_pt_diff = abs(away_score - home_score)
            print(f"new max pt diff: {self._max_pt_diff}")
        if home_score > away_score:
            self.get_team(away_team)._game(
                False,
                self.get_team(home_team),
                'L',
                home_score,
                away_score,
                self._weeks_complete
            )
            self.get_team(home_team)._game(
                True,
                self.get_team(away_team),
                'W',
                home_score,
                away_score,
                self._weeks_complete
            )
        elif home_score < away_score:
            self.get_team(away_team)._game(
                False,
                self.get_team(home_team),
                'W',
                away_score,
                home_score,
                self._weeks_complete
            )
            self.get_team(home_team)._game(
                True,
                self.get_team(away_team),
                'L',
                away_score,
                home_score,
                self._weeks_complete
            )
        else:
            self.get_team(away_team)._game(
                False,
                self.get_team(home_team),
                'T',
                away_score,
                home_score,
                self._weeks_complete
            )
            self.get_team(home_team)._game(
                True,
                self.get_team(away_team),
                'T',
                away_score,
                home_score,
                self._weeks_complete
            )


    def week_complete(self):
        self._weeks_complete += 1
        print(f"week {self._weeks_complete} complete.")
        for team in self._teams.values():
            if len(team.get_week()) < self._weeks_complete:
                team._bye()
            team._set_last4()
            team._set_sos()
        self._power_rankings(week_complete=True)
        self._set_tiers()
        self.save_season_data()
    
    
    def save_season_data(self, week=None):
        season_data = deepcopy(vars(self))
        season_data['_teams'] = {
            team.get_code(): team._save_season_data()
            for team in self._teams.values()
        }
        if week == None:
            file_name = f"data/week{self._weeks_complete}.json"
        else:
            file_name = f"data/week{week}.json"
        file = open(file_name, "wt")
        json.dump(season_data, file)
        file.close()
        print(f"season data successfully exported as {file_name}")
    
    
    def set_legacy_power_scores(self, scores_dict):
        for code, score in scores_dict.items():
            self.get_team(code)._set_legacy_power_score(score)
        self.save_season_data()
    
    
    def set_prev_playoff_scores(self, scores_dict):
        for code, score in scores_dict.items():
            self.get_team(code)._set_prev_playoff_score(score)
        self.save_season_data()
        

    def _power_rankings(self, week_complete=False):
        for team in self._teams.values():
            team._set_power_score(self._max_pt_diff, week_complete=week_complete)
        ll = [value for value in self._teams.values()]
        ll.sort(key=lambda dd: (dd.get_power_score(),
                                dd.get_win_percentage(),
                                dd.get_total_pt_diff()
                               ),
                reverse=True
               )
        for i in range(len(ll)):
            self._teams[ll[i].get_code()]._set_power_ranking(i+1, week_complete=week_complete)
        self._max_power_score = self._teams[ll[0].get_code()].get_power_score()
        self._min_power_score = self._teams[ll[-1].get_code()].get_power_score()
        for team in self._teams.values():
            team._set_scaled_power_score(self._min_power_score, self._max_power_score)
    
    
    def _set_tiers(self):
        for team in self._teams.values():
            team._set_tier()
    
    
    def _edit_all_teams_json(self, attr, week, values_dict):
        filename = f"data/week{week}.json"
        file = open(filename)
        data = json.load(file)
        file.close()
        for team in self._teams.values():
            data = team._edit_json(attr, week, values_dict[team.get_code()], data=data)
        file = open(filename, "wt")
        json.dump(data, file)
        file.close()
        print(f"{filename} successfully edited: all teams, week{week}, {attr}")


class Team:


    def __init__(self, name, code, div, _wins=0, _losses=0, _ties=0, _win_percentage=0, _win_percentage_history=None, _total_pt_diff=0, _health=1, _health_history=None, _starting_qb=True, _starting_qb_history=None, _week=None, _last4=0, _sos=0, _power_score=0, _scaled_power_score=0, _tier=None, _power_ranking=None, _power_ranking_history=None, _power_score_history=None, _legacy_power_score=0, _prev_playoff_score=0, _current_playoff_score=0):
        self._name = name
        self._code = code
        self._division = div
        self._wins = _wins
        self._losses = _losses
        self._ties = _ties
        self._win_percentage = _win_percentage
        self._win_percentage_history = _win_percentage_history if _win_percentage_history is not None else []
        self._total_pt_diff = _total_pt_diff
        self._health = _health
        self._health_history = _health_history if _health_history is not None else [1]
        self._starting_qb = _starting_qb
        self._starting_qb_history = _starting_qb_history if _starting_qb_history is not None else [True]
        self._week = _week if _week is not None else []
        self._last4 = _last4
        self._sos = _sos
        self._power_score = _power_score
        self._power_score_history = _power_score_history if _power_score_history is not None else []
        self._scaled_power_score = _scaled_power_score
        self._legacy_power_score = _legacy_power_score
        self._prev_playoff_score = _prev_playoff_score
        self._current_playoff_score = _current_playoff_score
        self._power_ranking = _power_ranking
        self._power_ranking_history = _power_ranking_history if _power_ranking_history is not None else []
        self._tier = _tier


    def __str__(self):
        return self._name


    def get_name(self):
        return self._name


    def get_code(self):
        return self._code


    def get_win_percentage(self):
        return self._win_percentage


    def get_power_score(self):
        return self._power_score


    def get_week(self):
        return self._week


    def get_total_pt_diff(self):
        return self._total_pt_diff
    
    
    def _save_season_data(self):
        season_data = deepcopy(vars(self))
        for week in season_data['_week']:
            del week['opp']
        return season_data
    
    
    def build_df(self):
        out = [self._power_ranking, self._tier, self._name, self._wins, self._losses, self._ties,
               self._win_percentage, self._total_pt_diff, self._sos, self._last4, self._power_score,
               self._scaled_power_score
              ]
        for week in self._week:
            out.extend([f"{week['result']:>8}", week['opp_string'],
                        week['score'], week['opp_score']
                       ])
        return out


    def _game(self, home, opp, result, winning_score, losing_score, weeks_complete):
        if len(self._week) != weeks_complete:
            raise ValueError(f"Error: A game for '{self._code}' is either missing or you're trying to enter too many games for this team. Game not saved.")
        try:
            opp_code = opp.get_code()
        except AttributeError:
            opp_code = 'bye'
        if home:
            modifier = "vs. "
        else:
            modifier = "@ "
        opp_string = modifier + opp_code.upper()
        week = {
            'week': len(self._week) + 1,
            'home': home,
            'opp': opp,
            'opp_code': opp_code,
            'opp_string': opp_string,
            'result': result
        }
        if result == 'W':
            self._wins += 1
            self._total_pt_diff += winning_score - losing_score
            week['score'] = winning_score
            week['opp_score'] = losing_score
        elif result == 'L':
            self._losses += 1
            self._total_pt_diff += losing_score - winning_score
            week['score'] = losing_score
            week['opp_score'] = winning_score
        else:
            self._ties += 1
            week['score'] = winning_score
            week['opp_score'] = losing_score
        self._week.append(week)
        self._win_percentage = (self._wins + self._ties/2) / (self._wins + self._losses + self._ties)
        self._win_percentage_history.append(self._win_percentage)


    def _bye(self):
        self._week.append(
            {'home': 'bye', 'opp': 'bye', 'opp_string': 'bye', 'result': 'bye', 'score': 0,
             'opp_score': 0
            }
        )


    def _set_last4(self):
        start_index = max(0, len(self._week)-4)
        count = 0
        for i in range(start_index, len(self._week)):
            if self._week[i]['result'] == "W":
                count += 1
        self._last4 = count


    def _set_sos(self):
        out = 0
        for week in self._week:
            try:
                out += week['opp'].get_win_percentage()
            except AttributeError:
                pass
        self._sos = out
    
    
    def _set_legacy_power_score(self, score):
        self._legacy_power_score = score
    
    
    def _set_prev_playoff_score(self, score):
        self._prev_playoff_score = score


    def _set_power_score(self, max_pt_diff, week_complete=False):
        # oppwin + ptdiff*(oppwin or 1-oppwin)/maxptdiff - 1 if lose
        if week_complete:
            self._power_score_history.append(0)
        if len(self._power_score_history) != len(self._week):
            raise Exception(f"error: len({self._code}._power_score_history) != len({self._code}._week)")
        for i in range(len(self._week)):
            diff = self._week[i]['score'] - self._week[i]['opp_score']
            try:
                opp_win_percentage = self._week[i]['opp']._win_percentage
            except AttributeError:
                opp_win_percentage = 0
            if diff >= 0:
                score = opp_win_percentage + diff * opp_win_percentage / max_pt_diff
            else:
                score = opp_win_percentage + diff * (1 - opp_win_percentage) / max_pt_diff - 1
            self._power_score_history[i] = score
        start_index = max(0, len(self._power_score_history)-4)
        self._power_score = sum(self._power_score_history)
        self._power_score += sum(self._power_score_history[start_index:])
        self._power_score += self._legacy_power_score * max(0, 1 - len(self._power_score_history) / 4)
        self._power_score += max(0, self._prev_playoff_score-len(self._power_score_history))


    def _set_scaled_power_score(self, min_power_score, max_power_score):
        try:
            self._scaled_power_score = (self._power_score - min_power_score) / (max_power_score - min_power_score)
        except ZeroDivisionError:
            self._scaled_power_score = 1


    def _set_power_ranking(self, power_ranking, week_complete=False):
        self._power_ranking = power_ranking
        if week_complete:
            self._power_ranking_history.append(power_ranking)
        else:
            self._power_ranking_history[-1] = power_ranking


    def _set_tier(self):
        tier = 1
        power = self._scaled_power_score
        if power < 5/6:
            tier += 1
        if power < 2/3:
            tier += 1
        if power < 1/2:
            tier += 1
        if power < 1/3:
            tier += 1
        if power < 1/6:
            tier += 1
        self._tier = tier
    
    
    def _edit_json(self, attr, week, value, data=None):
        dump = False
        if data == None:
            dump = True
            filename = f"data/week{week}.json"
            file = open(filename)
            data = json.load(file)
            file.close()
        if type(attr) != list:
            if value != None:
                data['_teams'][self._code][attr] = value
            else:
                del data['_teams'][self._code][attr]
        else: 
            if value != None:
                data['_teams'][self._code][attr[0]][attr[1]] = value
            else:
                del data['_teams'][self._code][attr[0]][attr[1]]
        if dump:
            file = open(filename, "wt")
            json.dump(data, file)
            file.close()
            print(f"{filename} successfully edited: {self.get_code()}, week{week}, {attr}")
        else:
            return data

